# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :hostname => 'manager01', :ip => '192.168.77.10', :ram => 2048, :cpus => 1 },
  { :hostname => 'worker01', :ip => '192.168.77.12', :ram => 2048, :cpus => 1 },
  { :hostname => 'worker02', :ip => '192.168.77.13', :ram => 2048, :cpus => 1 }
]

Vagrant.configure("2") do |config|


  # config.vm.boot_timeout = 300
  # vagrant-hostmanager options
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = false
  # Always use Vagrant's insecure key
  #config.ssh.insert_key = false
  # Forward ssh agent to easily ssh into the different machines
  config.ssh.forward_agent = true
  # Vagrant box
#   config.vm.box = "bento/ubuntu-18.04"
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  # Docker
#   config.vm.provision "docker"
  # Synced Folder
  config.vm.synced_folder '.', '/vagrant'

  # Provision nodes
  nodes.each do |node|
    config.vm.define node[:hostname] do |config|
      config.vm.hostname = node[:hostname]
      config.vm.network :private_network, ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 2048;
      cpus = node[:cpus] ? node[:cpus] : 2;

      config.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--memory", memory.to_s,
          "--cpus", cpus.to_s
        ]
      end 
      config.vm.provision :shell, path: "install.sh"

          # Provision manager01 using docker swarm init after the last VM is booted.
      if node[:hostname] == "manager01"
        config.vm.provision "shell", inline: <<-SHELL
          sudo timedatectl set-ntp true
          sudo usermod -aG docker $USER
          # sudo reboot
          docker swarm init --advertise-addr #{node[:ip]}:2377 --data-path-addr #{node[:ip]}
          echo "#{node[:ip]}" > /vagrant/manager01ip.txt
          docker swarm join-token -q worker > /vagrant/swarm_token.txt
          SHELL
      end

      if node[:hostname].start_with?("worker0")
        config.vm.provision "shell", inline: <<-SHELL
        sudo timedatectl set-ntp true
        sudo usermod -aG docker $USER
        MANAGER_IP=$(cat /vagrant/manager01ip.txt)
        WORKER_TOKEN=$(cat /vagrant/swarm_token.txt)  # Read from shared file
        echo "$WORKER_TOKEN"
        docker swarm join --advertise-addr #{node[:ip]} --listen-addr #{node[:ip]}:2377 --token $WORKER_TOKEN $MANAGER_IP:2377
        SHELL
      end
    end
  end
end

